### PR TITLE
Handle multiple input formats

### PR DESCRIPTION
**Pull request by padmalcom**
This pull requests allows to handle multiple inputs for the classifier:
- list of image paths
- list of ndarray (opencv frames)
- single image path
- single ndarray (opencv frame)

### CODE REVIEW

**Comment by bedapudi6788** [comment]
@padmalcom if I understand this correctly, you added support for passing opencv image to .classify directly, right?

**Comment by padmalcom** [comment]
Exactly, detect() allows passing opencv frames, but classify() didn't, so I added a check for the parameter type and did the conversion where required.

**Comment by bedapudi6788** [comment]
although undocumented, classify too allows opencv frames, but only when passed as a batch.

for example, the following works.

```python
import cv2
from nudenet import NudeClassifier
classifier = NudeClassifier()
classifier.classify([cv2.imread('image.jpg')])
```

**Comment by padmalcom** [comment]
Okay, I wasn't aware of that option. Feel free to reject or accept the pull request.

**Comment by bedapudi6788** [comment]
@padmalcom thanks for the report and suggested fix.

updated this by https://github.com/notAI-tech/NudeNet/blob/6ebf23727bf4f13abc6391410d78d1f3693a54c5/nudenet/classifier.py#L111 .

available from nudenet>=2.0.9

**Pull request closed without merging**
